// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sparseinv2
NumericVector sparseinv2(int n, IntegerVector Lp, IntegerVector Li, NumericVector Lx, NumericVector d, IntegerVector Up, IntegerVector Uj, NumericVector Ux, IntegerVector Zp, IntegerVector Zi);
RcppExport SEXP _sparseinv_sparseinv2(SEXP nSEXP, SEXP LpSEXP, SEXP LiSEXP, SEXP LxSEXP, SEXP dSEXP, SEXP UpSEXP, SEXP UjSEXP, SEXP UxSEXP, SEXP ZpSEXP, SEXP ZiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Lp(LpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Li(LiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Lx(LxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Up(UpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Uj(UjSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Ux(UxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Zp(ZpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Zi(ZiSEXP);
    rcpp_result_gen = Rcpp::wrap(sparseinv2(n, Lp, Li, Lx, d, Up, Uj, Ux, Zp, Zi));
    return rcpp_result_gen;
END_RCPP
}
