# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparseinv2 <- function(n, Lp, Li, Lx, d, Up, Uj, Ux, Zp, Zi) {
    .Call(`_sparseinv_sparseinv2`, n, Lp, Li, Lx, d, Up, Uj, Ux, Zp, Zi)
}

